import React from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import Card from '../components/ui/Card';
import { Trophy, Target, Zap, LayoutDashboard, Flame, BookOpen } from 'lucide-react';
import { getProgress } from '../utils/progressManager';

const DOMAINS = [
  { key: 'dsa',      label: 'DSA',              color: '#4f9cf9' },
  { key: 'ml',       label: 'ML',               color: '#a855f7' },
  { key: 'webdev',   label: 'Web Dev',           color: '#22c55e' },
  { key: 'dbms',     label: 'DBMS',              color: '#f97316' },
  { key: 'os',       label: 'OS',               color: '#ef4444' },
  { key: 'networks', label: 'Networks',          color: '#06b6d4' },
];

const Profile = () => {
  const { user } = useAuth();
  const navigate = useNavigate();

  if (!user) {
    return (
      <div className="container mx-auto px-6 py-32 text-center h-[70vh] flex flex-col items-center justify-center gap-8">
        <div className="w-24 h-24 rounded-full bg-surface border border-card-border flex items-center justify-center text-text-secondary">
          <LayoutDashboard size={48} />
        </div>
        <div>
          <h2 className="text-4xl font-syne mb-2">Access Denied</h2>
          <p className="text-text-secondary">Please sign in to view your diagnostic profile.</p>
        </div>
      </div>
    );
  }

  const progress = getProgress(user.email);
  const totalAssessments = progress.totalAssessments || 0;
  const streak = progress.streak || 0;

  // Compute per-domain progress
  const domainStats = DOMAINS.map(d => {
    const dp = progress[d.key] || { currentLevel: 1, unlockedLevels: [1], scores: {} };
    const levelsPassed = Object.values(dp.scores || {}).filter(s => s.passed).length;
    const scores = Object.values(dp.scores || {});
    const avgScore = scores.length ? Math.round(scores.reduce((acc, s) => acc + s.percent, 0) / scores.length) : 0;
    return { ...d, levelsPassed, avgScore, currentLevel: dp.currentLevel };
  });

  // Top domain
  const topDomain = [...domainStats].sort((a, b) => b.avgScore - a.avgScore)[0];

  // Total levels passed across all domains
  const totalLevelsPassed = domainStats.reduce((acc, d) => acc + d.levelsPassed, 0);

  const metrics = [
    { icon: <Target />, label: 'Assessments Taken', value: totalAssessments || '0' },
    { icon: <Trophy className="text-yellow-400" />, label: 'Levels Passed', value: `${totalLevelsPassed} / 60` },
    { icon: <Zap />, label: 'Top Domain', value: topDomain.avgScore > 0 ? topDomain.label : '—' },
    { icon: <Flame className="text-orange-400" />, label: 'Day Streak', value: streak > 0 ? `${streak} 🔥` : '0' },
  ];

  const handleDownloadPDF = () => {
    const lines = domainStats.map(d =>
      `${d.label.padEnd(16)} Levels Passed: ${d.levelsPassed}/10  Avg Score: ${d.avgScore}%`
    ).join('\n');
    const reportContent = `SKILLMIRROR DIAGNOSTIC REPORT
==============================
Student: ${user?.name || 'Student'}
Email:   ${user?.email || ''}
Date:    ${new Date().toLocaleDateString()}

ASSESSMENT SUMMARY
------------------
Total Assessments:  ${totalAssessments}
Total Levels Passed: ${totalLevelsPassed} / 60
Day Streak:         ${streak}

DOMAIN BREAKDOWN
----------------
${lines}

Generated by SkillMirror — AI Student Performance Evaluator
Creator: Jaanvi Chouhan | github.com/Jaanvichouhan34
`;
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SkillMirror_Report_${(user?.name || 'Student').replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container mx-auto px-6 py-20 flex flex-col gap-12">

      {/* Header */}
      <section className="flex flex-col md:flex-row items-center gap-8 text-center md:text-left">
        <div className="w-32 h-32 rounded-full bg-gradient-main flex items-center justify-center text-5xl font-syne font-extrabold text-white shadow-glow">
          {user.initials}
        </div>
        <div className="space-y-2">
          <h1 className="text-4xl md:text-5xl font-syne capitalize">{user.name}</h1>
          <p className="text-text-secondary text-lg">{user.email}</p>
          <div className="flex gap-4 items-center justify-center md:justify-start">
            <span className="text-sm font-bold text-accent-blue bg-accent-blue/10 px-3 py-1 rounded-full uppercase tracking-tighter">Pro Member</span>
            <span className="text-sm text-text-secondary">Joined Jan 2026</span>
          </div>
        </div>
      </section>

      {/* Metrics */}
      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {metrics.map((m, i) => (
          <Card key={i} className="p-6 flex flex-col items-center gap-4 text-center">
            <div className="w-12 h-12 rounded-xl bg-surface border border-card-border flex items-center justify-center text-accent-blue">
              {m.icon}
            </div>
            <div>
              <p className="text-text-secondary text-xs font-bold uppercase tracking-widest mb-1">{m.label}</p>
              <h3 className="text-3xl font-bold">{m.value}</h3>
            </div>
          </Card>
        ))}
      </section>

      {/* Domain Progress */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Start Assessment CTA */}
        <Card className="lg:col-span-1 flex flex-col items-center justify-center p-12 text-center gap-6 bg-gradient-to-br from-accent-blue/10 to-accent-purple/10 border-accent-blue/20 overflow-hidden relative">
          <div className="absolute top-0 right-0 w-32 h-32 bg-accent-blue/10 blur-3xl rounded-full" />
          <BookOpen size={48} className="text-accent-blue" />
          <div>
            <h3 className="text-2xl font-bold mb-2">Assessment Engine</h3>
            <p className="text-text-secondary text-sm">6 domains · 10 levels each · 10 questions per level</p>
          </div>
          <button
            onClick={() => navigate('/assessment')}
            className="w-full py-4 bg-accent-blue text-white font-bold rounded-xl hover:scale-105 transition-transform active:scale-95"
          >
            Begin Assessment →
          </button>
          <button
            onClick={handleDownloadPDF}
            className="w-full py-3 border border-white/20 text-white font-bold rounded-xl hover:bg-white/5 transition-all text-sm"
          >
            ⬇ Download Report
          </button>
        </Card>

        {/* Domain Progress Bars */}
        <Card className="lg:col-span-2 flex flex-col gap-6 p-10">
          <div>
            <h3 className="text-2xl font-bold">Domain Progress</h3>
            <p className="text-text-secondary text-sm">Levels passed per domain (10 levels each)</p>
          </div>
          <div className="space-y-6 mt-2">
            {domainStats.map((d, i) => (
              <div key={d.key} className="space-y-2 cursor-pointer group" onClick={() => navigate(`/assessment/levels/${d.key}`)}>
                <div className="flex justify-between text-sm font-bold">
                  <span className="group-hover:text-white transition-colors">{d.label}</span>
                  <span style={{ color: d.color }}>{d.levelsPassed}/10 levels · {d.avgScore}% avg</span>
                </div>
                <div className="h-3 bg-white/5 rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${d.levelsPassed * 10}%` }}
                    transition={{ duration: 1, delay: i * 0.1 }}
                    className="h-full rounded-full"
                    style={{ background: d.color }}
                  />
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>

    </div>
  );
};

export default Profile;
